# Generated by Django 4.2.3 on 2023-07-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='marca',
            name='apellido',
            field=models.CharField(help_text='Apellido del cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='cedula',
            field=models.CharField(help_text='Cedula del Cliente', max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='ciudad',
            field=models.CharField(help_text='Ciudad del cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='direccion',
            field=models.CharField(help_text='Dirección del cliente', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='nombre',
            field=models.CharField(help_text='Nombre del cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='subcategoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inv.subcategoria'),
        ),
        migrations.AddField(
            model_name='marca',
            name='telefono',
            field=models.CharField(help_text='Teléfono del cliente', max_length=15, null=True),
        ),
    ]
