# Generated by Django 4.2.3 on 2023-07-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_remove_marca_descripcion_marca_apellido_marca_cedula_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('subcategoria', 'cedula')},
        ),
    ]
