# Generated by Django 4.2.3 on 2023-07-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_alter_marca_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='marca',
            name='subcategoria',
        ),
    ]
